repos:
  - repo: local
    hooks:
      - entry: build-harness install --check
        id: install-check
        language: system
        name: Virtual environment installed dependencies are current
        pass_filenames: false

  - repo: local
    hooks:
      - entry: build-harness formatting
        id: formatting
        language: system
        name: Black, isort formatting passes
        pass_filenames: false

  - repo: local
    hooks:
      - entry: build-harness static-analysis --analysis flake8
        id: flake8
        language: system
        name: Build harness flake8 analysis passes
        pass_filenames: false

  - repo: local
    hooks:
      - entry: build-harness static-analysis --analysis mypy
        id: mypy
        language: system
        name: Build harness mypy analysis passes
        pass_filenames: false

  - repo: local
    hooks:
      - entry: build-harness static-analysis --analysis pydocstyle
        id: static-analysis
        language: system
        name: Build harness pydocstyle analysis passes
        pass_filenames: false

  - repo: local
    hooks:
      # now that unit tests take some time to complete, this check embodies both coverage test and unit tests check
      # run unit tests manually to figure out which tests are causing a failure
      # have to avoid executing manual tests here
      # Don't forget to update the coverage threshold in .gitlab-ci.yml
      - entry: build-harness unit-test --test-dir tests/ci --check 90
        id: unit-test-check
        language: system
        name: Coverage analysis passes
        pass_filenames: false
